baseURL = "https://blog.houstonp.com/"
DefaultContentLanguage = "en"
title = "Houston Perrett"

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[services.rss]
  limit = 1

[Params]
  subtitle = "Thoughts on actuarial, insurance, technology, and society."
  # logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  comments = false
  readingTime = false
  mathEngine = "mathjax"
  selfHosted = true

[Params.author]
  name = "Houston Perrett"
  website = "https://houstonp.com"
  email = "hp@houstonp.com"
  github = "houstonwp"
  twitter = "HoustonPerrett"
  linkedin = "https://linkedin.com/in/HoustonPerrett"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    name = "Home"
    url = "https://houstonp.com"
    weight = 1

[[menu.main]]
    name = "Disclaimer"
    url = "disclaimer"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[outputs]
home = ["HTML", "RSS", "LegacyRSS"]
section  = ["HTML"]

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "index"

[outputFormats.LegacyRSS]
mediaType = "application/rss+xml"
baseName = "rss"
isPlainText = true
noUgly = true
notAlternative = true

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true
