baseurl = "/"
DefaultContentLanguage = "en"
title = "Houston Perrett"
theme = "beautifulhugo"
metaDataFormat = "toml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-67480960-1"

[services.rss]
  limit = 1

[Params]
  subtitle = "Thoughts on actuarial, insurance, technology, and society."
 # logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  comments = false
  readingTime = false

[Author]
  name = "Houston Perrett"
  website = "https://houstonp.com"
  email = "hp@houstonp.com"
  github = "houstonwp"
  twitter = "HoustonPerrett"
  linkedin = "HoustonPerrett"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    name = "Home"
    url = "https://houstonp.com"
    weight = 1

[[menu.main]]
    name = "Disclaimer"
    url = "disclaimer"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "Subscribe"
    url = "subscribe"
    weight = 4

[outputs]
home = [ "RSS", "HTML"]
section  = ["HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"
